### ISSUE TITLE
Cannot find imports.

### ISSUE THREAD

**Issue by danielkatanski** [PeterStaev/lego-spikeprime-mindstorms-vscode#51]
When I enter code into VScode the import of hub and utime or PrimeHub are not found.

What am I doing wrong?

![image](https://user-images.githubusercontent.com/25781446/196196883-fd5946d0-f630-47a5-9d0f-181d28961365.png)

**Comment by PeterStaev** [comment]
Hey @danielkatanski , the plugin does not extend the auto complete provided by the native python libraries. That's why the functions are not recognized. Still they will work when you deploy to the brick. You can check https://github.com/PeterStaev/lego-spikeprime-mindstorms-vscode/issues/29#issuecomment-1141176834 and https://github.com/PeterStaev/lego-spikeprime-mindstorms-vscode/issues/29#issuecomment-1166307963 for partial workarounds.

**Comment by danielkatanski** [comment]
Peter,

 

I just discovered that.

 

1) My current problem is how do I instantiate and use my external class?

 

It keeps complaining that it is not there.  I tried loading it into slop 19 thinking it could find it.  Any ideas?  Can I download two programs into one slot?

 

2) Also, can I make a master program run other programs in other slots?

 

I know that I am asking a lot, but this thing has lots of computing power.  It should act like any other computer and OS.

 

I am a FLL coach trying to build an environment for the 4th and 5th graders to code in.

 

Dan Katanski

734-474-3045

**Comment by PeterStaev** [comment]
@danielkatanski #13 tracks ability to upload multi project files. To my understanding is that the brick right now allows a single file per slot via their API. Also I haven't seen any API to execute a program from another program.

**Comment by danielkatanski** [comment]
Peter,

 

Is there any way to reboot the Spike Prime?  Cycling the power sometimes is not enough.

 

The EV3 had a Vulcan Death grip to reboot the device.

 

The only instructions that I haver seen about the spike is to reset it back to factory defaults.

 

Thank you for your time.

 

Dan

**Comment by PeterStaev** [comment]
Not aware of such a thing.
